NodeClassMap = {
    "REROUTE" : "/Script/Engine.MaterialExpressionReroute",
    # Constant
    "VALUE" : "/Script/Engine.MaterialExpressionConstant",
    "RGB" : "/Script/Engine.MaterialExpressionConstant3Vector",
    "RGBA" : "/Script/Engine.MaterialExpressionConstant4Vector",
    "VECTOR" : "/Script/Engine.MaterialExpressionConstant3Vector",
    "VECT_TRANSFORM" : "/Script/Engine.MaterialExpressionTransform",
    "_POINT_TRANSFORM" : "/Script/Engine.MaterialExpressionTransformPosition",
    # Input
    "UVMAP" : "/Script/Engine.MaterialExpressionTextureCoordinate",
    "VERTEX_COLOR" : "/Script/Engine.MaterialExpressionVertexColor",
    "OBJECT_INFO" : "/Script/Engine.MaterialExpressionObjectPositionWS",
    "CAMERA" : "/Script/Engine.MaterialExpressionCameraVectorWS",
    "_CAMERA_DEPTH" : "/Script/Engine.MaterialExpressionPixelDepth",
    "FRESNEL" : "/Script/Engine.MaterialExpressionCustom",
    "_NORMALWS" : "/Script/Engine.MaterialExpressionPixelNormalWS",
    "_CAMVECWS" : "/Script/Engine.MaterialExpressionCameraVectorWS",
    # Texture coordinate
    "TEX_COORD" : "/Script/Engine.MaterialExpressionTextureCoordinate",
    "_NORMALOS" : "/Script/Engine.MaterialExpressionPixelNormalWS",
    "_UV" : "/Script/Engine.MaterialExpressionTextureCoordinate",
    "_OBJ_POS" : "/Script/Engine.MaterialExpressionWorldPosition",
    "_CAM_POS" : "/Script/Engine.MaterialExpressionWorldPosition",
    "_WIN_POS" : "/Script/Engine.MaterialExpressionScreenPosition",
    # Geometry
    "NEW_GEOMETRY" : "/Script/Engine.MaterialExpressionWorldPosition",
    "_NORMALWS" : "/Script/Engine.MaterialExpressionPixelNormalWS",
    "_TANGENTWS" : "/Script/Engine.MaterialExpressionVertexTangentWS",
    "_VERTEX_NORMAlWS" : "/Script/Engine.MaterialExpressionVertexNormalWS",
    "_INCOMMING" : "/Script/Engine.MaterialExpressionCustom",
    "_CAMERA_POS" : "/Script/Engine.MaterialExpressionCameraPositionWS",
    # Mix
    "MIX_RGB" : "/Script/Engine.MaterialExpressionCustom",
    # Combine
    "COMBXYZ" : "/Script/Engine.MaterialExpressionMaterialFunctionCall",
    "COMBRGB" : "/Script/Engine.MaterialExpressionMaterialFunctionCall",
    # Separate
    "SEPXYZ" : "/Script/Engine.MaterialExpressionMaterialFunctionCall",
    "SEPRGB" : "/Script/Engine.MaterialExpressionMaterialFunctionCall",
    "GAMMA" : "/Script/Engine.MaterialExpressionPower",
    # Math Node Two Input
    "ADD" : "/Script/Engine.MaterialExpressionAdd",
    "SUBTRACT" : "/Script/Engine.MaterialExpressionSubtract",
    "MULTIPLY" : "/Script/Engine.MaterialExpressionMultiply",
    "DIVIDE" : "/Script/Engine.MaterialExpressionDivide",
    "POWER" : "/Script/Engine.MaterialExpressionPower",
    "MINIMUM" : "/Script/Engine.MaterialExpressionMin",
    "MAXIMUM" : "/Script/Engine.MaterialExpressionMax",
    "MODULO" : "/Script/Engine.MaterialExpressionFmod",
    "ARCTAN2" : "/Script/Engine.MaterialExpressionArctangent2Fast",
    # Math Node One Input
    "SQRT" : "/Script/Engine.MaterialExpressionSquareRoot",
	"ABSOLUTE" : "/Script/Engine.MaterialExpressionAbs",
	"ROUND" : "/Script/Engine.MaterialExpressionRound",
	"FLOOR" : "/Script/Engine.MaterialExpressionFloor",
	"CEIL" : "/Script/Engine.MaterialExpressionCeil",
	"FRACT" : "/Script/Engine.MaterialExpressionFrac",
	"SINE" : "/Script/Engine.MaterialExpressionSine",
	"COSINE" : "/Script/Engine.MaterialExpressionCosine",
	"TANGENT" : "/Script/Engine.MaterialExpressionTangent",
	"ARCSINE" : "/Script/Engine.MaterialExpressionArcsineFast",
	'ARCCOSINE': "/Script/Engine.MaterialExpressionArccosineFast",
	"ARCTANGENT" : "/Script/Engine.MaterialExpressionArctangentFast",
	"SIGN" : "/Script/Engine.MaterialExpressionSign",
	"TRUNC" : "/Script/Engine.MaterialExpressionTruncate",
    # Vector Math Two Input
    "CROSS_PRODUCT" : "/Script/Engine.MaterialExpressionCrossProduct",
    "DOT_PRODUCT": "/Script/Engine.MaterialExpressionDotProduct",
    "DISTANCE" : "/Script/Engine.MaterialExpressionDistance",
    "SCALE" : "/Script/Engine.MaterialExpressionMultiply",
    # Vector Math One Input
    "NORMALIZE" : "/Script/Engine.MaterialExpressionNormalize",
    "LENGTH" : "/Script/Engine.MaterialExpressionDistance",
    # Converter
    "BLACKBODY" : "/Script/Engine.MaterialExpressionBlackBody",
    "RGBTOBW" : "/Script/Engine.MaterialExpressionCustom",
    "CLAMP" : "/Script/Engine.MaterialExpressionClamp",
}

NodeNameMap = {
    "REROUTE" : "MaterialExpressionReroute",
    # Constant
    "VALUE" : "MaterialExpressionConstant",
    "RGB" : "MaterialExpressionConstant3Vector",
    "RGBA" : "MaterialExpressionConstant4Vector",
    "VECTOR" : "MaterialExpressionConstant3Vector",
    "VECT_TRANSFORM" : "MaterialExpressionTransform",
    "_POINT_TRANSFORM" : "MaterialExpressionTransformPosition",
    # Input
    "UVMAP" : "MaterialExpressionTextureCoordinate",
    "VERTEX_COLOR" : "MaterialExpressionVertexColor",
    "OBJECT_INFO" : "MaterialExpressionObjectPositionWS",
    "CAMERA" : "MaterialExpressionCameraVectorWS",
    "_CAMERA_DEPTH" : "MaterialExpressionPixelDepth",
    "FRESNEL" : "MaterialExpressionCustom",
    "_NORMALWS" : "MaterialExpressionPixelNormalWS",
    "_CAMVECWS" : "MaterialExpressionCameraVectorWS",
    # Texture coordinate
    "TEX_COORD" : "MaterialExpressionTextureCoordinate",
    "_NORMALOS" : "MaterialExpressionPixelNormalWS",
    "_UV" : "MaterialExpressionTextureCoordinate",
    "_OBJ_POS" : "MaterialExpressionWorldPosition",
    "_CAM_POS" : "MaterialExpressionWorldPosition",
    "_WIN_POS" : "MaterialExpressionScreenPosition",
    # Geometry
    "NEW_GEOMETRY" : "MaterialExpressionWorldPosition",
    #"_NORMALWS" : "MaterialExpressionPixelNormalWS",
    "_TANGENTWS" : "MaterialExpressionVertexTangentWS",
    "_VERTEX_NORMAlWS" : "MaterialExpressionVertexNormalWS",
    "_INCOMMING" : "MaterialExpressionCustom",
    "_CAMERA_POS" : "MaterialExpressionCameraPositionWS",
    # Mix
    "MIX_RGB" : "MaterialExpressionCustom",
    # Combine
    "COMBXYZ" : "MaterialExpressionMaterialFunctionCall",
    "COMBRGB" : "MaterialExpressionMaterialFunctionCall",
    # Separate
    "SEPXYZ" : "MaterialExpressionMaterialFunctionCall",
    "SEPRGB" : "MaterialExpressionMaterialFunctionCall",
    "GAMMA" : "MaterialExpressionPower",
    # Math Node Two Input
    "ADD" : "MaterialExpressionAdd",
    "SUBTRACT" : "MaterialExpressionSubtract",
    "MULTIPLY" : "MaterialExpressionMultiply",
    "DIVIDE" : "MaterialExpressionDivide",
    "POWER" : "MaterialExpressionPower",
    "MINIMUM" : "MaterialExpressionMin",
    "MAXIMUM" : "MaterialExpressionMax",
    "MODULO" : "MaterialExpressionFmod",
    "ARCTAN2" : "MaterialExpressionArctangent2Fast",
    # Math Node One Input
    "SQRT": "MaterialExpressionSquareRoot",
	"ABSOLUTE": "MaterialExpressionAbs",
	"ROUND": "MaterialExpressionRound",
	"FLOOR": "MaterialExpressionFloor",
	"CEIL": "MaterialExpressionCeil",
	"FRACT": "MaterialExpressionFrac",
	"SINE": "MaterialExpressionSine",
	"COSINE": "MaterialExpressionCosine",
	"TANGENT": "MaterialExpressionTangent",
	"ARCSINE": "MaterialExpressionArcsineFast",
	"ARCCOSINE": "MaterialExpressionArccosineFast",
	"ARCTANGENT": "MaterialExpressionArctangentFast",
	"SIGN": "MaterialExpressionSign",
	"TRUNC": "MaterialExpressionTruncate",
    # Vector Math Two Input
    "CROSS_PRODUCT" : "MaterialExpressionCrossProduct",
    "DOT_PRODUCT": "MaterialExpressionDotProduct",
    "DISTANCE" : "MaterialExpressionDistance",
    "SCALE" : "MaterialExpressionMultiply",
    # Vector Math One Input
    "NORMALIZE" : "MaterialExpressionNormalize",
    "LENGTH" : "MaterialExpressionDistance",
    # Converter
    "BLACKBODY" : "MaterialExpressionBlackBody",
    "RGBTOBW" : "MaterialExpressionCustom",
    "CLAMP" : "MaterialExpressionClamp",
}